services:
  php:
    build:
      context: "../back"
      dockerfile: "../env/php/Dockerfile"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - postgres:postgres
    volumes:
      - ../back:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    networks:
      - book_store

  nginx:
    build:
      context: "../front"
      dockerfile: "../env/nginx/Dockerfile"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ../back:/app
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - book_store
    links:
      - php:php

  postgres:
    image: 'postgres:16-alpine'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: bookstore
      POSTGRES_DB: bookstore
    restart: unless-stopped
    networks:
      - book_store

networks:
  book_store:

